# dependabot is annoying especially on a fork repo so we will temporary disable (uncheck to reuse)

#version: 2
#updates:
#  - package-ecosystem: "npm" # See documentation for possible values
#    directory: "/" # Location of package manifests
#    schedule:
#      interval: "daily"